use crate::models::{FirewallConfig, PortSpec, Protocol};

/// Generate the contents of firewall.nix from a FirewallConfig
pub fn generate_firewall_nix(config: &FirewallConfig) -> String {
    let mut out = String::new();

    out.push_str("# Fichier genere par Nix Firewall Manager - Ne pas editer manuellement\n");
    out.push_str("# Generated by Nix Firewall Manager - Do not edit manually\n");

    // Write rule name metadata as comments for persistence across reboots
    for rule in &config.rules {
        if !rule.enabled {
            continue;
        }
        let proto = match rule.protocol {
            Protocol::Tcp => "tcp",
            Protocol::Udp => "udp",
            Protocol::Both => "both",
        };
        let ports_str = match &rule.ports {
            PortSpec::Single(p) => p.to_string(),
            PortSpec::Range(from, to) => format!("{}-{}", from, to),
            PortSpec::Multiple(ports) => ports
                .iter()
                .map(|p| p.to_string())
                .collect::<Vec<_>>()
                .join(","),
        };
        out.push_str(&format!("# nfm:rule:{}:{}:{}\n", rule.name, proto, ports_str));
    }

    out.push_str("{ lib, config, pkgs, ... }:\n\n");
    out.push_str("{\n");
    out.push_str("  networking.firewall = {\n");

    // enable
    out.push_str(&format!(
        "    enable = {};\n",
        if config.enabled { "true" } else { "false" }
    ));

    // allowedTCPPorts
    let tcp_ports = config.all_tcp_ports();
    out.push_str(&format!(
        "    allowedTCPPorts = [ {} ];\n",
        tcp_ports
            .iter()
            .map(|p| p.to_string())
            .collect::<Vec<_>>()
            .join(" ")
    ));

    // allowedUDPPorts
    let udp_ports = config.all_udp_ports();
    out.push_str(&format!(
        "    allowedUDPPorts = [ {} ];\n",
        udp_ports
            .iter()
            .map(|p| p.to_string())
            .collect::<Vec<_>>()
            .join(" ")
    ));

    // allowedTCPPortRanges
    let tcp_ranges = config.all_tcp_ranges();
    if tcp_ranges.is_empty() {
        out.push_str("    allowedTCPPortRanges = [];\n");
    } else {
        out.push_str("    allowedTCPPortRanges = [\n");
        for range in &tcp_ranges {
            out.push_str(&format!(
                "      {{ from = {}; to = {}; }}\n",
                range.from, range.to
            ));
        }
        out.push_str("    ];\n");
    }

    // allowedUDPPortRanges
    let udp_ranges = config.all_udp_ranges();
    if udp_ranges.is_empty() {
        out.push_str("    allowedUDPPortRanges = [];\n");
    } else {
        out.push_str("    allowedUDPPortRanges = [\n");
        for range in &udp_ranges {
            out.push_str(&format!(
                "      {{ from = {}; to = {}; }}\n",
                range.from, range.to
            ));
        }
        out.push_str("    ];\n");
    }

    // trustedInterfaces
    if config.trusted_interfaces.is_empty() {
        out.push_str("    trustedInterfaces = [];\n");
    } else {
        out.push_str(&format!(
            "    trustedInterfaces = [ {} ];\n",
            config
                .trusted_interfaces
                .iter()
                .map(|i| format!("\"{}\"", i))
                .collect::<Vec<_>>()
                .join(" ")
        ));
    }

    out.push_str("  };\n");
    out.push_str("}\n");

    out
}
